import type { PiWebPlugin, ThemeTokens } from "../types";

const classicTokens = {
  "--pi-bg": "#0a0a0b",
  "--pi-surface": "#141416",
  "--pi-surface-hover": "#202023",
  "--pi-terminal-bg": "#050506",
  "--pi-terminal-text": "#f4f4f5",
  "--pi-border": "#303033",
  "--pi-border-muted": "#222225",
  "--pi-text": "#f4f4f5",
  "--pi-text-secondary": "#d4d4d8",
  "--pi-text-bright": "#fafafa",
  "--pi-muted": "#a1a1aa",
  "--pi-dim": "#71717a",
  "--pi-accent": "#e4e4e7",
  "--pi-accent-border": "#a1a1aa",
  "--pi-selection-bg": "#242426",
  "--pi-success": "#86a98c",
  "--pi-success-border": "#5e7d64",
  "--pi-success-bg": "#172019",
  "--pi-success-surface": "#202b22",
  "--pi-success-ring": "#86a98c55",
  "--pi-warning": "#c7a56a",
  "--pi-warning-border": "#907542",
  "--pi-warning-surface": "#292318",
  "--pi-danger": "#d98b8b",
  "--pi-purple": "#b0b0b8",
  "--pi-purple-border": "#85858d",
  "--pi-purple-surface": "#242427",
  "--pi-overlay": "#0008",
  "--pi-shadow-soft": "#0006",
  "--pi-shadow": "#0008",
  "--pi-shadow-strong": "#000b",
  "--pi-bg-overlay-soft": "#0a0a0bdd",
  "--pi-bg-overlay": "#0a0a0be6",
  "--pi-success-bg-overlay": "#172019ee",
  "--pi-terminal-selection": "#3a3a40",
} satisfies ThemeTokens;

const piWebDarkTokens = {
  "--pi-bg": "#09090b",
  "--pi-surface": "#121214",
  "--pi-surface-hover": "#1c1c1f",
  "--pi-terminal-bg": "#050506",
  "--pi-terminal-text": "#f4f4f5",
  "--pi-border": "#27272a",
  "--pi-border-muted": "#1f1f23",
  "--pi-text": "#f4f4f5",
  "--pi-text-secondary": "#a1a1aa",
  "--pi-text-bright": "#fafafa",
  "--pi-muted": "#71717a",
  "--pi-dim": "#52525b",
  "--pi-accent": "#e4e4e7",
  "--pi-accent-border": "#a1a1aa",
  "--pi-selection-bg": "#222225",
  "--pi-success": "#86a98c",
  "--pi-success-border": "#5e7d64",
  "--pi-success-bg": "#172019",
  "--pi-success-surface": "#202b22",
  "--pi-success-ring": "#86a98c55",
  "--pi-warning": "#c7a56a",
  "--pi-warning-border": "#907542",
  "--pi-warning-surface": "#292318",
  "--pi-danger": "#d98b8b",
  "--pi-purple": "#b0b0b8",
  "--pi-purple-border": "#85858d",
  "--pi-purple-surface": "#242427",
  "--pi-overlay": "#0008",
  "--pi-shadow-soft": "#0006",
  "--pi-shadow": "#0008",
  "--pi-shadow-strong": "#000b",
  "--pi-bg-overlay-soft": "#09090bdd",
  "--pi-bg-overlay": "#09090be6",
  "--pi-success-bg-overlay": "#172019ee",
  "--pi-terminal-selection": "#3a3a40",
} satisfies ThemeTokens;

const piWebLightTokens = {
  "--pi-bg": "#fafafa",
  "--pi-surface": "#ffffff",
  "--pi-surface-hover": "#f4f4f5",
  "--pi-terminal-bg": "#18181b",
  "--pi-terminal-text": "#fafafa",
  "--pi-border": "#e4e4e7",
  "--pi-border-muted": "#f0f0f2",
  "--pi-text": "#18181b",
  "--pi-text-secondary": "#3f3f46",
  "--pi-text-bright": "#09090b",
  "--pi-muted": "#71717a",
  "--pi-dim": "#a1a1aa",
  "--pi-accent": "#18181b",
  "--pi-accent-border": "#52525b",
  "--pi-selection-bg": "#f0f0f1",
  "--pi-success": "#507058",
  "--pi-success-border": "#6f9278",
  "--pi-success-bg": "#edf3ee",
  "--pi-success-surface": "#e2ebe3",
  "--pi-success-ring": "#50705855",
  "--pi-warning": "#886d3c",
  "--pi-warning-border": "#a38a5a",
  "--pi-warning-surface": "#f5f0e7",
  "--pi-danger": "#a85f5f",
  "--pi-purple": "#5f5f66",
  "--pi-purple-border": "#85858d",
  "--pi-purple-surface": "#eeeeef",
  "--pi-overlay": "#18181b66",
  "--pi-shadow-soft": "#18181b22",
  "--pi-shadow": "#18181b33",
  "--pi-shadow-strong": "#18181b44",
  "--pi-bg-overlay-soft": "#fafafadd",
  "--pi-bg-overlay": "#fafafae6",
  "--pi-success-bg-overlay": "#edf3eeee",
  "--pi-terminal-selection": "#a1a1aa",
} satisfies ThemeTokens;

export const themePackPlugin: PiWebPlugin = {
  apiVersion: 4,
  name: "PI WEB Themes",
  activate: () => ({
    contributions: {
      themes: [
        {
          id: "pi-web-dark",
          name: "PI WEB Dark",
          description: "Dark PI WEB palette.",
          order: 10,
          colorScheme: "dark",
          tokens: piWebDarkTokens,
        },
        {
          id: "pi-web-light",
          name: "PI WEB Light",
          description: "Light PI WEB palette.",
          order: 20,
          colorScheme: "light",
          tokens: piWebLightTokens,
        },
        {
          id: "classic",
          name: "PI WEB Classic",
          description: "The original PI WEB dark palette.",
          order: 30,
          colorScheme: "dark",
          tokens: classicTokens,
        },
      ],
      themePairs: [
        {
          id: "pi-web",
          name: "PI WEB",
          description: "Follow the system light/dark preference with PI WEB themes.",
          order: 10,
          light: "pi-web-light",
          dark: "pi-web-dark",
        },
      ],
    },
  }),
};
